### ISSUE TITLE
idea: Use CMake for support for cross platform compiling.

### ISSUE THREAD

**Issue by kevinalavik** [Limine-Bootloader/limine-c-template-x86-64#1]
It would be nice if it used CMake or like meson for support for cross platform compiling.

**Comment by Mintsuki** [comment]
The template is already cross platform to pretty much anything but native Windows (not WSL). Using cmake, meson, or other build systems is outside the scope of this template.

**Comment by kevinalavik** [comment]
> The template is already cross platform to pretty much anything but native Windows (not WSL). Using cmake, meson, or other build systems is outside the scope of this template.

@mintsuki it would be nice to have native Windows support :)
