### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by bondarukid** [Limine-Bootloader/limine-c-template-x86-64#2]
./kernel/get-deps
make: ./kernel/get-deps: No such file or directory
make: *** [GNUmakefile:67: kernel-deps] Error 127

**Comment by Mintsuki** [comment]
Have you deleted that file? If not, it should work.

But more generally, a lot of context is lacking to know what is going on.

**Comment by bondarukid** [comment]
No, I placed the files from the repository in a separate folder and tried to run the build.

**Comment by Mintsuki** [comment]
Then it should work, unless you misplaced relative to the rest of the repo, renamed, or removed `kernel/get-deps`.
